use_frameworks!

target 'XR_CommonTool_Example' do
  pod 'XR_CommonTool', :path => '../'

  target 'XR_CommonTool_Tests' do
    inherit! :search_paths
    
    pod 'UMCCommon'
    pod 'UMCAnalytics'
    pod 'UMCSecurityPlugins'
    
  end
end
